name: WeatherByLocation
version: 0.2.9
main: mc.spigot.weatherbylocation.WeatherByLocation
api-version: 1.13
commands:
  set-weather-location:
    description: Set the latitude and longitude to use for weather data.
    usage: /set-weather-location XX.XXX YY.YYY
    permission: weatherbylocation.set-weather-location
  get-weather-location:
    description:  Get the latitude and longitude used for weather data.
    usage: /get-weather-location
    permission: weatherbylocation.set-weather-location
  set-weather-update-interval:
    description: Set the update interval in minutes for our weather data.
    usage: /set-weather-update-interval XX
    permission: weatherbylocation.set-weather-location
permissions:
  set-weather-location:
    description: Allows you to set the location used to pull weather data.
    default: op